Image load clarification
MaximIntegratedAI/MAX78000_SDK pull request #36
Opened 2021-04-15 02:32 UTC by vicloginov

2021-04-15 15:24 UTC, aniktash reviewed
sounds good

2021-04-15 20:34 UTC, rotx-maxim approved these changes

2021-11-15 20:28 UTC, rotx-maxim requested changes
You are changing all the working Unix openocd command lines to Windows versions. Could we have both please?

2021-11-16 20:08 UTC, vicloginov commented
I will fix it

2021-11-16 23:10 UTC, aniktash reviewed
looks ok

2021-11-16 23:10 UTC, aniktash commented on Examples/MAX78000/CNN/rps-demo/README.md
> +3.  Open 'rgb.py' file and change the name of the image file on line 8. im = (Image.open('./image\_filename.format')). Save the changes.
Image.open('image_filename.format')

2021-11-18 15:44 UTC, rotx-maxim approved these changes

2021-12-10 17:27 UTC, merged