Update board make file to use OV7692 driver as default.
MaximIntegratedAI/MAX78000_SDK pull request #48
Opened 2021-11-11 01:35 UTC by aniktash

2021-11-11 01:38 UTC, vicloginov reviewed
Looks good

2021-11-15 20:27 UTC, rotx-maxim requested changes
Please fix the path separator / \ issues.

2021-11-15 20:27 UTC, rotx-maxim commented on Examples/MAX78000/CNN/cats-dogs_demo/README.md
> +<img src="Resources\eclipse_board.png" style="zoom:33%;" />
in HTML, this needs to be a forward slash

2021-11-15 20:27 UTC, rotx-maxim commented on Examples/MAX78000/CNN/cats-dogs_demo/README.md
> +<img src="Resources\fthr_tft.png" style="zoom: 50%;" />
/

2021-11-15 20:27 UTC, rotx-maxim commented on Examples/MAX78000/CNN/cats-dogs_demo/README.md
> +3.  Open 'rgb.py' file and change the name of the image file on line 8. im = (Image.open('./image\_filename.format')). Save the changes.
In Python, we need os.path.join()

2021-11-15 22:16 UTC, aniktash commented on Examples/MAX78000/CNN/cats-dogs_demo/README.md
> +3.  Open 'rgb.py' file and change the name of the image file on line 8. im = (Image.open('./image\_filename.format')). Save the changes.
removed ./image, The step 2 instructs to copy to the same folder.

2021-11-16 15:08 UTC, rotx-maxim requested changes
One more \

2021-11-16 15:08 UTC, rotx-maxim commented on Examples/MAX78000/CNN/cats-dogs_demo/README.md
> +3.  Open 'rgb.py' file and change the name of the image file on line 8. im = (Image.open('image\_filename.format')). Save the changes.
/

2021-11-16 15:41 UTC, rotx-maxim approved these changes

2021-11-17 01:55 UTC, vicloginov reviewed
Looks great!

2021-12-10 17:29 UTC, closed without merging